# Default values for gpu-scheduler-check
# This is a YAML-formatted file.

# Image configuration
image:
  repository: gpulab.azurecr.io/gpu-scheduler-check
  pullPolicy: Always
  tag: "latest"

# Image pull secrets
imagePullSecrets: []

# Service account configuration
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  name: ""

# Pod annotations - includes the GPU scheduling map
podAnnotations:
  gpu-scheduling-map: |
    0=aks-workerpool-25338008-vmss000000:0,1
    1=aks-workerpool-25338008-vmss000001:2
    2=aks-workerpool-25338008-vmss000003:0,1,2
    3=aks-workerpool-25338008-vmss000004:3
    4=aks-workerpool-25338008-vmss000004:3

# Pod security context
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

# Container security context
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: false  # Set to false because we write health check files
  runAsNonRoot: true
  runAsUser: 1000

# Resource limits and requests
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

# Node selector
nodeSelector: {}

# Tolerations
tolerations: []

# Affinity
affinity: {}

# Replica count - using StatefulSet for predictable naming
replicaCount: 5

# StatefulSet configuration
statefulSet:
  # Use StatefulSet for predictable pod naming (pod-0, pod-1, etc.)
  enabled: true
  serviceName: "gpu-scheduler-check"
  podManagementPolicy: "Parallel"

# Scheduler configuration
scheduler:
  # Specify the custom GPU scheduler
  name: "gpu-scheduler"

# Environment variables for pod information
env:
  - name: NODE_NAME
    valueFrom:
      fieldRef:
        fieldPath: spec.nodeName
  - name: POD_NAME
    valueFrom:
      fieldRef:
        fieldPath: metadata.name
  - name: POD_NAMESPACE
    valueFrom:
      fieldRef:
        fieldPath: metadata.namespace
  - name: POD_IP
    valueFrom:
      fieldRef:
        fieldPath: status.podIP

# Health checks
healthCheck:
  enabled: true
  livenessProbe:
    initialDelaySeconds: 10
    periodSeconds: 30
    timeoutSeconds: 5
    failureThreshold: 3
  readinessProbe:
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 3

# Service configuration (for potential monitoring)
service:
  enabled: false
  type: ClusterIP
  port: 8080

# Extra volumes
extraVolumes: []

# Extra volume mounts  
extraVolumeMounts: [] 