{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "gpu-scheduler.fullname" . }}
  labels:
    {{- include "gpu-scheduler.labels" . | nindent 4 }}
rules:
# Core permissions for scheduling
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "patch", "update"]
  
- apiGroups: [""]
  resources: ["pods/binding"]
  verbs: ["create"]
  
- apiGroups: [""]
  resources: ["pods/status"]
  verbs: ["patch", "update"]

# Node permissions for validation and placement
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]

# Event permissions for logging scheduling decisions
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch", "update"]

# Namespace permissions
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "watch"]

# ConfigMap permissions (for configuration)
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]

# PersistentVolume permissions (for scheduling decisions)
- apiGroups: [""]
  resources: ["persistentvolumes"]
  verbs: ["get", "list", "watch"]

- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list", "watch"]

# Storage class permissions
- apiGroups: ["storage.k8s.io"]
  resources: ["storageclasses"]
  verbs: ["get", "list", "watch"]

# CSI permissions
- apiGroups: ["storage.k8s.io"]
  resources: ["csinodes"]
  verbs: ["get", "list", "watch"]

# Priority class permissions
- apiGroups: ["scheduling.k8s.io"]
  resources: ["priorityclasses"]
  verbs: ["get", "list", "watch"]

# Resource quota permissions
- apiGroups: [""]
  resources: ["resourcequotas"]
  verbs: ["get", "list", "watch"]

# Service permissions (for service affinity)
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch"]

# ReplicaSet and Deployment permissions (for owner references)
- apiGroups: ["apps"]
  resources: ["replicasets", "deployments"]
  verbs: ["get", "list", "watch"]

# StatefulSet permissions (for owner references) 
- apiGroups: ["apps"]
  resources: ["statefulsets"]
  verbs: ["get", "list", "watch"]

# Pod disruption budget permissions
- apiGroups: ["policy"]
  resources: ["poddisruptionbudgets"]
  verbs: ["get", "list", "watch"]
{{- end }} 